import { Metadata } from "next";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "NextJs Tutorial - Parna", // Displays NextJs Tutorial - Parna in the browser tab for the pages that don't have a title in their metadata
    template: "%s | Parna - Js",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <header>
          <p className="bg-blue-200 p-4">Header</p>
        </header>
        {children}
        <footer>
          <p className="bg-blue-200 p-4">Footer</p>
        </footer>
      </body>
    </html>
  );
}
